global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'test-service'
    static_configs:
      - targets: ['host.docker.internal:5000']  # or 172.17.0.1:5000

  # - job_name: 'api-gateway'
  #   static_configs:
  #     - targets: ['host.docker.internal:5000']

  # - job_name: 'auth-service'
  #   static_configs:
  #     - targets: ['host.docker.internal:5001']

  # - job_name: 'user-service'
  #   static_configs:
  #     - targets: ['host.docker.internal:5002']